services:
  freertos:
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    build: .
    ports:
      - "2222:22"
    restart: unless-stopped
    volumes:
      - ./:/FreeRTOS
    # network_mode: host

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
