version: "3.8"
services:
  freertos:
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    build: .
    ports:
      - "2222:22"
    restart: unless-stopped
    volumes:
      - ./:/FreeRTOS
