@startuml
skinparam linetype ortho

' Classes definition
class NTPTask {
    + void vStartNTPClientTasks_SingleTasks(uint16_t, UBaseType_t)
}

class NTP_main_utility {
    + struct ntp_p* find_assoc(struct ntp_r*)
    + digest md5(int)
    + struct ntp_r* recv_packet()
    + void xmit_packet(struct ntp_x*)
}

class NTP_TDMG {
    + void assoc_table_init(Assoc_table*, uint32_t*)
    + void settime(tstamp)
    + tstamp gettime()
}

class NTP_peer {
    + void packet(struct ntp_p*, struct ntp_r*)
    + void clock_filter(struct ntp_p*, double, double, double)
    + void clear(struct ntp_p*)
    + int access(struct ntp_r*)
    + void receive(struct ntp_r*)
}

class NTP_poll {
    + void poll_update(struct ntp_p*, int)
}

class NTP_system_process {
    + void clock_select()
    + void clock_update(struct ntp_p*)
    + void clock_combine()
}

 class NTP_vfo {
    + local_clock(struct ntp_p*, double)
    + void rstclock(int, offset, double)
    + void clock_adjust()
}

' Relationships
NTPTask -left-> NTP_main_utility
NTPTask -down-> NTP_peer
NTPTask -left-> NTP_vfo

NTP_main_utility -left-> NTP_peer
NTP_main_utility -left-> NTP_TDMG.c

NTP_TDMG -down-> NTP_main_utility

NTP_poll -right-> NTP_peer

NTP_peer -left-> NTP_TDMG
NTP_peer -left-> NTP_poll
NTP_peer -left-> NTP_system_process
NTP_peer -right-> NTP_main_utility

NTP_system_process -down-> NTP_vfo
NTP_system_process -down-> NTP_TDMG
NTP_system_process -down-> NTP_peer

NTP_vfo -left-> NTP_main_utility
@enduml