name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
    - name: run check-format.sh
      run: ./check-format.sh
